In [130]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import models

from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.preprocessing.image import img_to_array

import matplotlib.pyplot as plt

In [131]:
model = models.load_model("FFNN2.h5")

In [95]:
cnn_model = models.load_model("CNN_MNIST.h5")

In [127]:
def load_image(filename):
    # load the image
    img = load_img(filename, grayscale=True, target_size=(28, 28))
    # convert to array
    img = img_to_array(img)
    # reshape into a single sample with 1 channel
#     img = img.reshape(1, 28, 28, 1)
    img = img.reshape(1,28,28,1)
    # prepare pixel data
    img = img.astype('float32')
    img = img / 255.0
#     print(img)
    return img

In [128]:
def run_example():
    # load the image
    img = load_image('test_imgs/7.png')
    # load model
    #cnn_model = models.load_model("CNN_MNIST.h5")
    # predict the class
    digit = cnn_model.predict_classes(img)
    print(digit[0])
#     print(digit)

In [ ]:
run_example()

In [134]:
img = load_img('test_imgs/7.png', grayscale=True, target_size=(28, 28))
# convert to array
img = img_to_array(img)
print(img)
# reshape into a single sample with 1 channel
#     img = img.reshape(1, 28, 28, 1)
img = img.reshape(1,28,28,1)
# prepare pixel data
img = img.astype('float32')
img = img / 255.0

[[[179.]
  [179.]
  [178.]
  [178.]
  [178.]
  [177.]
  [177.]
  [177.]
  [179.]
  [177.]
  [179.]
  [178.]
  [179.]
  [181.]
  [178.]
  [177.]
  [179.]
  [175.]
  [182.]
  [178.]
  [175.]
  [179.]
  [177.]
  [180.]
  [178.]
  [178.]
  [178.]
  [178.]]

 [[179.]
  [179.]
  [178.]
  [178.]
  [178.]
  [177.]
  [177.]
  [177.]
  [175.]
  [177.]
  [179.]
  [182.]
  [176.]
  [175.]
  [181.]
  [178.]
  [176.]
  [180.]
  [179.]
  [180.]
  [179.]
  [181.]
  [177.]
  [177.]
  [177.]
  [177.]
  [177.]
  [177.]]

 [[178.]
  [178.]
  [178.]
  [178.]
  [178.]
  [177.]
  [177.]
  [177.]
  [169.]
  [171.]
  [173.]
  [177.]
  [180.]
  [180.]
  [180.]
  [179.]
  [181.]
  [176.]
  [174.]
  [173.]
  [183.]
  [175.]
  [179.]
  [182.]
  [177.]
  [177.]
  [177.]
  [177.]]

 [[178.]
  [178.]
  [178.]
  [178.]
  [177.]
  [177.]
  [177.]
  [177.]
  [176.]
  [172.]
  [180.]
  [179.]
  [177.]
  [180.]
  [177.]
  [179.]
  [178.]
  [181.]
  [183.]
  [176.]
  [178.]
  [173.]
  [180.]
  [178.]
  [178.]
  [178.]
  [1

In [133]:
digit = cnn_model.predict_classes(img)
print(digit[0])

8
